=== Vasumitraa/XML/2-exercice.dtd
<!ELEMENT annuaire (personnes)>
<!ELEMENT personnes (personne+)>

<!ELEMENT personne (nom, prenom+, genre, adresse, telephones, emails)>
<!ATTLIST personne id ID #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT genre (#PCDATA)>

<!ELEMENT adresse (pays, ville, rue, numero)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT numero (#PCDATA)>

<!ELEMENT telephones (telephone+)>
<!ELEMENT telephone (#PCDATA)>
<!ATTLIST telephone type (portable | fixe | bureau) #IMPLIED>

<!ELEMENT emails (email+)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email type (personnelle | professionnelle) #IMPLIED>

=== Vasumitraa/XML/2-exercice.xml
<?xml version="1.0" encoding="UTF8"?>
<!DOCTYPE annuaire SYSTEM "2-exercice.dtd">
<annuaire>   
    <personnes>
        <personne id="P1">
            <nom>Pascal</nom>
            <prenom>Cathleen</prenom>
            <genre>Femme</genre> <!-- transformer genre en attribut -->
            <adresse>
                <pays>Belgique</pays>
                <ville>Schaerbeek</ville>
                <rue>Alexandre M********</rue>
                <numero>119</numero>
            </adresse>
            <telephones>
                <telephone type="portable">0456/**.**.**</telephone>
                <telephone type="fixe"></telephone>
                <telephone type="bureau"></telephone>
            </telephones>
            <emails>
                <email type="personnelle">pascal.cathleen****@gmail.com</email>
                <email type="professionnelle"></email>
            </emails>
        </personne>
        <personne id="P2">
            <nom>Pascal</nom>
            <prenom>Faustine</prenom>
            <genre>Agenre</genre>
            <adresse>
                <pays>Belgique</pays>
                <ville>Schaerbeek</ville>
                <rue>Alexandre M********</rue>
                <numero>119</numero>
            </adresse>
            <telephones>
                <telephone type="portable">0456/**.**.**</telephone>
                <telephone type="fixe"></telephone>
                <telephone type="bureau"></telephone>
            </telephones>
            <emails>
                <email type="personnelle">pascal.faustine****@gmail.com</email>
                <email type="professionnelle"></email>
            </emails>
        </personne>
    </personnes>
</annuaire>
